# color
export TERM="xterm-256color"


# load theme
source "${HOME}/.dotfiles/zsh/theme"

# load zgen
source "${HOME}/.dotfiles/zgen/zgen.zsh"

# load fzf confing
source "${HOME}/.dotfiles/zsh/fzf.zsh"

# autojump 
source /etc/profile.d/autojump.zsh


# check if there's no init script
if ! zgen saved; then
    echo "Creating a zgen save"

    zgen oh-my-zsh

    # plugins
    zgen oh-my-zsh plugins/git
    zgen oh-my-zsh plugins/virtualenvwrapper
    zgen oh-my-zsh plugins/systemd
    zgen oh-my-zsh plugins/fzf
    zgen oh-my-zsh plugins/pass
    zgen oh-my-zsh plugins/archlinux
    zgen oh-my-zsh plugins/vi-mode
    zgen oh-my-zsh plugins/extract
    zgen oh-my-zsh plugins/sudo
    zgen oh-my-zsh plugins/docker
    zgen oh-my-zsh plugins/last-working-dir
    zgen oh-my-zsh plugins/themes
    zgen oh-my-zsh plugins/common-aliases
    zgen oh-my-zsh plugins/history-substring-search
    zgen oh-my-zsh plugins/pip
    zgen oh-my-zsh plugins/python
    zgen load zsh-users/zsh-autosuggestions
    zgen load zsh-users/zsh-syntax-highlighting

    # theme
    zgen load bhilburn/powerlevel9k powerlevel9k

    # save all to init script
    zgen save
fi

bindkey '^ ' autosuggest-execute

eval "$(pyenv init -)"

export FZF_BASE="/usr/bin/fzf"
export ZSH_AUTOSUGGEST_HIGHLIGHT_STYLE="fg=242"
export TOMBS="$HOME/Tombs"
export PASSWORD_STORE_TOMB_FILE="$TOMBS/pass.tomb" # for pass-tomb
export PASSWORD_STORE_TOMB_KEY="$TOMBS/my/pass.tomb.key" # for pass-tomb
source /usr/bin/virtualenvwrapper.sh
export FZF_DEFAULT_OPTS="--height 40% --layout=reverse --preview '[[ \$(file --mime {}) =~ binary ]] && echo {} is a binary file || (highlight -O ansi -l {} || cat {}) 2> /dev/null | head -500' "
export MATPLOTLIBRC="$HOME/.matplotlib"
export PATH="$PATH:$HOME/Downloads/julia-1.3.1/bin"
export VIRTUALENVWRAPPER_PYTHON="$HOME/.pyenv/shims/python"
export PATH=$PATH:~/.emacs.d/bin



setopt HIST_IGNORE_SPACE

alias vim='nvim'
