[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    automatic_update = true
    bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"
    autocomplete_method = "coc"


[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'top'
  default_height = 30

[[layers]]
  name = "lang#python"

# helps coc to work better
[[layers]] 
  name = 'lsp'
  filetypes = [
    'python'
  ]
#  [layers.override_cmd]
#    c = ['ccls', '--log-file=/tmp/ccls.log']
#    cpp = ['ccls', '--log-file=/tmp/ccls.log']


