[options]
    colorscheme = "gruvbox"
    colorscheme_bg = "dark"
    enable_guicolors = true
    statusline_separator = "arrow"
    statusline_inactive_separator = "arrow"
    buffer_index_type = 4
    enable_tabline_filetype_icon = true
    enable_statusline_mode = false
    automatic_update = true
    vimcompatible = true
    filemanager = "vimfiler"
    
    # dont add options after this line
    # bootstrap_before = "myspacevim#before"
    bootstrap_after = "myspacevim#after"


[[layers]]
  name = 'autocomplete'
  auto-completion-return-key-behavior = "complete"
  auto-completion-tab-key-behavior = "smart"

[[layers]]
  name = 'shell'
  default_position = 'bottom'
  default_height = 25

[[layers]]
  name = "lang#python"
